
/**
 * This file was generated by the extract tool.
 * Do not modify this file manually.
 * 
 */

/**
 * The type of string constrained to the field names of the TsTestTable
 */
export type FieldNameType = 'id' | 'name' | 'age' | 'cash' | 'dep';


/**
 * The entity type of the TsTestTable
 */
export interface TsTestTable {
	id: number;
	name: string;
	age?: number;
	cash?: number;
	dep?: string;
}

/**
 * The data-column names list of the TsTestTable
 */
export const FIELD_NAMES: readonly FieldNameType[] = Object.freeze(['id', 'name', 'age', 'cash', 'dep']);

/**
 * The source-of-truth resource name resource name (database table name) of the TsTestTable
 */
export const RESOURCE_NAME = 'ts_test_table';

/**
 * The data-column name set of the TsTestTable
 */
export const FieldNameSet: ReadonlySet<FieldNameType> = Object.freeze(new Set(FIELD_NAMES));

/**
 * Create a new TsTestTable with the default values set if not provided
 */
export function build(input: TsTestTable): TsTestTable {
    return {
			age: 9,
			cash: 4.2,
			dep: "dev-\"big\"'BIG'",
      ...input,
    };
}
