name: Release

on: 
  push:
    tags:
    - 'v*'

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "release.md"

  publish:
    needs: archive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    #----------------------------------------------
    #  -----  Install Python  -----
    #----------------------------------------------
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install --no-interaction
    #----------------------------------------------
    #         Publish the package
    #----------------------------------------------
    - name: Publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
